version: '3'

services:

  bot:
    expose:
      - "5000"
    build:
      context: .
      dockerfile: Dockerfile.staging
    environment:
      - NODE_ENV=staging

  mongodb:
    ports:
      - "27017:27017"
  nginx_bot:
    image: nginx:latest
    networks:
      - eyewitness-network
    volumes:
      - ./nginx/bot-staging.conf:/etc/nginx/nginx.conf
      - ./nginx/bot_logs:/var/log/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "5000:5006"

  nginx_read-server:
    image: nginx:latest
    networks:
      - eyewitness-network
    volumes:
      - ./nginx/rs-staging.conf:/etc/nginx/nginx.conf
      - ./nginx/rs_logs:/var/log/nginx/
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - "5001:5007"
