version: '3'

networks:

  eyewitness-network:
    driver: bridge

volumes:

  mongodb-data:
    driver: local

services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    environment:
      - TZ=Europe/London
      - ENTRY_POINT=bot
    volumes:
      - ./app:/src/app
      - ./lib:/src/lib
      - ./.env:/src/.env
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
    networks:
      - eyewitness-network
    tty: true
    restart: on-failure

  read-server:
    build:
      context: .
      dockerfile: Dockerfile.development
    env_file:
      - .env
    environment:
      - TZ=Europe/London
      - ENTRY_POINT=read-server
    volumes:
      - ./app:/src/app
      - ./lib:/src/lib
      - ./.env:/src/.env
      - ./package.json:/src/package.json
      - ./package-lock.json:/src/package-lock.json
    networks:
      - eyewitness-network
    tty: true
    restart: on-failure

  mongodb:
    image: mongo:3.4
    networks:
      - eyewitness-network
    command: mongod
    volumes:
      - mongodb-data:/data/db
    restart: on-failure

