version: '3'

# This is the default override for the development environment

services:

  bot:
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
    command: npm run start-development

  read-server:
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
    command: npm run start-development

  mongodb:
    ports:
      - "27017:27017"

  mongoclient:
    image: mongoclient/mongoclient:2.2.0
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongodb:27017/eyewitness
    networks:
      - eyewitness-network
    ports:
      - "3000:3000"
    restart: on-failure
